version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: pip install pylint
      - run: pip install black
      - run: pip install -e .
      - run: make run_checks
      - run: make run_tests
